const { Client } = require('pg');
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');
const { crypto } = require('crypto');
require('dotenv').config();

const dbConfig = {
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432', 10),
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
};

// Generates a random secure password if none is provided
function generateRandomPassword(length = 12) {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+';
  let password = '';
  for (let i = 0; i < length; i++) {
    const randomIndex = Math.floor(Math.random() * chars.length);
    password += chars[randomIndex];
  }
  return password;
}

async function init() {
  const targetDb = process.env.DB_NAME || 'ems_db';
  console.log(`🔄 Checking/Creating target database: "${targetDb}"...`);

  // 1. Connect to default 'postgres' database to ensure target exists
  const defaultClient = new Client({
    ...dbConfig,
    database: 'postgres',
  });

  try {
    await defaultClient.connect();
    const res = await defaultClient.query('SELECT 1 FROM pg_database WHERE datname = $1', [targetDb]);
    if (res.rowCount === 0) {
      console.log(`🔨 Creating database "${targetDb}"...`);
      await defaultClient.query(`CREATE DATABASE ${targetDb}`);
      console.log(`✅ Database "${targetDb}" created.`);
    } else {
      console.log(`ℹ️ Database "${targetDb}" already exists.`);
    }
  } catch (err) {
    console.error('❌ Database connection/creation failed:', err.message);
    process.exit(1);
  } finally {
    await defaultClient.end();
  }

  // 2. Connect to the target database
  const client = new Client({
    ...dbConfig,
    database: targetDb,
  });

  try {
    await client.connect();

    // Check if tables already exist by checking if 'users' table exists
    const tableCheck = await client.query(`
      SELECT COUNT(*)::int AS count 
      FROM pg_tables 
      WHERE schemaname = 'public' AND tablename = 'users'
    `);

    if (tableCheck.rows[0].count === 0) {
      console.log('📖 Table "users" not found. Applying database schema...');
      const schemaPath = path.join(__dirname, 'schema.sql');
      const schemaSql = fs.readFileSync(schemaPath, 'utf8');
      await client.query(schemaSql);
      console.log('✅ Database schema applied successfully.');
    } else {
      console.log('ℹ️ Database schema already applied.');
    }

    // 3. Check if there are any admin users in the database
    const adminCheck = await client.query("SELECT COUNT(*)::int AS count FROM users WHERE role = 'admin'");
    const adminCount = adminCheck.rows[0].count;

    if (adminCount > 0) {
      console.log('ℹ️ An Admin user already exists in the database. Setup skipped.');
    } else {
      // 4. Create the initial admin user
      const adminEmail = process.env.INITIAL_ADMIN_EMAIL || 'admin@ems.com';
      let adminPassword = process.env.INITIAL_ADMIN_PASSWORD;

      let isPasswordAutoGenerated = false;
      if (!adminPassword) {
        adminPassword = generateRandomPassword();
        isPasswordAutoGenerated = true;
      }

      console.log(`🔨 Creating initial Admin user with email: ${adminEmail}`);
      const hashedPassword = await bcrypt.hash(adminPassword, 10);

      await client.query(`
        INSERT INTO users (name, email, password_hash, role, is_active)
        VALUES ($1, $2, $3, 'admin', TRUE)
      `, ['System Administrator', adminEmail, hashedPassword]);

      console.log('✅ Initial Admin user created successfully.');
      console.log('================================================================');
      console.log('🔑 INITIAL ADMIN CREDENTIALS:');
      console.log(`   Email:    ${adminEmail}`);
      if (isPasswordAutoGenerated) {
        console.log(`   Password: ${adminPassword}  <-- WRITE THIS DOWN, IT WILL NOT BE SHOWN AGAIN!`);
      } else {
        console.log('   Password: [Specified in your .env file]');
      }
      console.log('================================================================');
    }

    console.log('🎉 Production database setup successfully complete!');
  } catch (err) {
    console.error('❌ Error during production database initialization:', err.message);
    process.exit(1);
  } finally {
    await client.end();
  }
}

init();
